bookmarklet/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from bookmarks import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^bookmarks/', include('bookmarks.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookmarks/urls.py
from django.conf.urls import url
from .views import index, show_category, add_category, add_page, register, \
    user_login, user_logout, track_url, like_category, suggest_category

app_name = 'bookmarks'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-category/$', add_category, name='add_category'),
    url(r'^category/(?P<category_slug>[\w\-]+)/add-page/$', add_page, name='add_page'),
    url(r'^category/(?P<category_slug>[\w\-]+)/$', show_category, name='show_category'),
    url(r'^register/$', register, name='register'),
    url(r'^login/$', user_login, name='login'),
    url(r'^logout/$', user_logout, name='logout'),
    url(r'^goto/$', track_url, name='goto'),
    url(r'^like/$', like_category, name='like'),
    url(r'^suggest/$', suggest_category, name='suggest_category')
]

bookmarklet/templates/base.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}
    Bookmarklet
    {% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.2.3/css/bulma.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

{% include 'navigation.html' %}

{% block content %}

{% endblock %}

<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</body>
</html>

bookmarklet/templates/navigation.html
<nav class="nav has-shadow">
    <div class="container">
        <div class="nav-left">
            <a class="nav-item is-brand title is-3" href="{% url 'bookmarks:index' %}">
                Bookmarklet
            </a>
        </div>

        <span class="nav-toggle">
    <span></span>
    <span></span>
    <span></span>
  </span>

        <div class="nav-right nav-menu">
            <a class="nav-item is-tab" href="{% url 'bookmarks:index' %}">
                Home
            </a>
            <a class="nav-item is-tab" href="{% url 'bookmarks:add_category' %}">
                Add Category
            </a>

            <span class="nav-item">
      {% if user.is_authenticated %}

          <a class="button" href="{% url 'bookmarks:logout' %}">
        <span>Logout</span>
      </a>

      {% else %}
          <a class="button" href="{% url 'bookmarks:login' %}">
        <span>Login</span>
      </a>
          <a class="button is-info" href="{% url 'bookmarks:register' %}">
        <span>Sign Up</span>
      </a>
      {% endif %}
    </span>
        </div>
    </div>
</nav>