bookmarklet/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from bookmarks import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^bookmarks/', include('bookmarks.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookmarks/urls.py
from django.conf.urls import url
from .views import index, show_category, add_category, add_page, register, \
    user_login, user_logout, track_url, like_category, suggest_category

app_name = 'bookmarks'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-category/$', add_category, name='add_category'),
    url(r'^category/(?P<category_slug>[\w\-]+)/add-page/$', add_page, name='add_page'),
    url(r'^category/(?P<category_slug>[\w\-]+)/$', show_category, name='show_category'),
    url(r'^register/$', register, name='register'),
    url(r'^login/$', user_login, name='login'),
    url(r'^logout/$', user_logout, name='logout'),
    url(r'^goto/$', track_url, name='goto'),
    url(r'^like/$', like_category, name='like'),
    url(r'^suggest/$', suggest_category, name='suggest_category')
]

bookmarks/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

bookmarks/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Category, Page, UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}), help_text="Category")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ['name']


class PageForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}), help_text="Title")
    url = forms.URLField(widget=forms.URLInput(attrs={'class': 'input'}), help_text="URL")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ['category']


class UserForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'input'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    website = forms.CharField(widget=forms.URLInput(attrs={'class': 'input'}))

    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

bookmarks/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from bookmarks.models import Category, Page
from .forms import CategoryForm, PageForm, UserForm, UserProfileForm

# Create your views here.


def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context = {
        'categories': category_list,
        'pages': page_list
    }
    return render(request, 'index.html', context)


def show_category(request, category_slug):
    context = {}

    try:
        category = Category.objects.get(slug=category_slug)
        category.views += 1
        category.save()
        pages = Page.objects.filter(category=category)
        context['category'] = category
        context['pages'] = pages
    except Category.DoesNotExist:
        context['category'] = None
        context['pages'] = None

    return render(request, 'category.html', context)


@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return redirect(index)
        else:
            print(form.errors)

    context = {
        'form': form
    }
    return render(request, 'add_category.html', context)


@login_required
def add_page(request, category_slug):
    try:
        category = Category.objects.get(slug=category_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return redirect(show_category, category_slug)
        else:
            print(form.errors)

    context = {
        'form': form,
        'category': category
    }

    return render(request, 'add_page.html', context)


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()
            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    context = {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered
    }

    return render(request, 'register.html', context)


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Your account is disabled')

        else:
            print('Invalid login details: {0}, {1}'.format(username, password))
            return HttpResponse('Invalid login details.')

    else:
        return render(request, 'login.html', {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def track_url(request):
    page_id = None
    url = '/bookmarks/'

    if request.method == 'GET':
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']

            try:
                page = Page.objects.get(id=page_id)
                page.views += 1
                page.save()
                url = page.url
            except:
                pass

    return redirect(url)


def like_category(request):
    if request.method == 'GET':
        likes = 0
        cat_id = request.GET['category_id']
        print(request.GET)
        if cat_id:
            cat = Category.objects.get(id=int(cat_id))
            if cat:
                likes = cat.likes + 1
                cat.likes = likes
                cat.save()

        return HttpResponse(likes)


def get_category_list(max_results=0, starts_with=''):
    cat_list = []
    if starts_with:
        cat_list = Category.objects.filter(name__startswith=starts_with)
    if len(cat_list) > max_results:
        cat_list = cat_list[:max_results]

    return cat_list


def suggest_category(request):
    cat_list = []
    starts_with = ''

    if request.method == 'GET':
        starts_with = request.GET['suggestion']

    cat_list = get_category_list(8, starts_with)
    categories = {cat.slug: cat.name for cat in cat_list}

    return JsonResponse(categories)

bookmarks/templates/add_category.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <h1 class="title is-1">Add a Category.</h1>
        <div class="columns">
            <div class="column">
                <form action="{% url 'bookmarks:add_category' %}" id="category-form" method="post">
                    {% csrf_token %}
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}
                    {% for field in form.visible_fields %}
                        {% if field.errors %}
                            <div class="notification is-danger">{{ field.errors }}</div>
                        {% endif %}
                        <label class="label">{{ field.help_text }}</label>
                        {{ field }}

                    {% endfor %}

                    <input class="button is-info" type="submit" name="submit" value="Create Category">

                </form>
            </div>
            <div class="column"></div>
        </div>
    </div>

{% endblock %}

bookmarks/templates/add_page.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <h1 class="title is-1">Add a Page.</h1>
        <div class="columns">
            <div class="column">
                <form action="/bookmarks/category/{{ category.slug }}/add-page/" id="page-form" method="post">
                    {% csrf_token %}
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}
                    {% for field in form.visible_fields %}
                        {% if field.errors %}
                            <div class="notification is-danger">{{ field.errors }}</div>
                        {% endif %}
                        <label class="label">{{ field.help_text }}</label>
                        {{ field }}

                    {% endfor %}

                    <input class="button is-info" type="submit" name="submit" value="Create Page">

                </form>
            </div>
            <div class="column"></div>
        </div>
    </div>

{% endblock %}

bookmarks/templates/category.html
{% extends 'base.html' %}
{% load bookmarks_template_tags %}

{% block content %}

    <div class="container">
        <div class="columns">

            <div class="column">
                {% get_all_categories category %}
            </div>

            <div class="column">
                {% if category %}
                    <nav class="panel">
                        <p class="panel-heading">
                            {{ category.name }}
                            <button class="button is-small" id="likes" data-catid="{{ category.id }}">Like</button>
                            <span class="tag is-info is-small" id="likes-count">{{ category.likes }} likes</span>
                            <span class="tag is-info is-small">{{ category.views }} views</span>

                        </p>

                        {% if pages %}
                            {% for page in pages %}
                                <a class="panel-block" href="{% url 'bookmarks:goto' %}?page_id={{ page.id }}"
                                   target="_blank">
                                    {{ page.title }}
                                    {% if page.views > 1 %}
                                        <span class="tag is-info is-small">{{ page.views }} views</span>
                                    {% elif page.views == 1 %}
                                        <span class="tag is-info is-small">{{ page.views }} view</span>
                                    {% endif %}
                                </a>
                            {% endfor %}
                        {% endif %}

                        {% if user.is_authenticated %}
                            <a class="button is-info panel-block"
                               href="{% url 'bookmarks:show_category' category.slug %}add-page/">Add Page</a>
                        {% endif %}

                        {% else %}
                        <p class="panel-block">No category found.</p>
                    </nav>
                {% endif %}
            </div>

        </div>
    </div>

{% endblock %}

bookmarks/templates/cats.html
{% if categories %}
    <p class="control">
        <input id="suggestion" name="suggestion" class="input" type="text" placeholder="Search Category">
    </p>
    <aside class="menu">
        <ul id="suggested-category-list" class="menu-list"></ul>
    </aside>
    <nav class="panel">
        <p class="panel-heading">
            All Categories
        </p>
        {% for category in categories %}
            {% if category == act_cat %}
                <a class="panel-block" href="{% url 'bookmarks:show_category' category.slug %}">
                    <strong>{{ category.name }}</strong></a>
            {% else %}
                <a class="panel-block" href="{% url 'bookmarks:show_category' category.slug %}">
                    {{ category.name }}
                </a>
            {% endif %}
        {% endfor %}

        {% else %}
        <p class="panel-block">No category found.</p>
    </nav>

{% endif %}

bookmarks/templates/index.html
{% extends 'base.html' %}
{% load bookmarks_template_tags %}

{% block content %}

    <div class="container">

        <div class="columns">
            <div class="column">
                {% get_all_categories category %}
            </div>
            <div class="column">
                {% if categories %}
                    <nav class="panel">
                        <p class="panel-heading">
                            Most Liked Categories
                        </p>
                        {% for category in categories %}
                            <a class="panel-block" href="{% url 'bookmarks:show_category' category.slug %}">
                                {{ category.name }}
                                {% if category.likes > 1 %}
                                    <span class="tag is-info is-small">{{ category.likes }} likes</span>
                                {% elif category.likes == 1 %}
                                    <span class="tag is-info is-small">{{ category.likes }} like</span>
                                {% endif %}
                            </a>
                        {% endfor %}

                        {% else %}
                        <p class="panel-block">No category found.</p>
                    </nav>

                {% endif %}
            </div>
            <div class="column">
                {% if pages %}
                    <nav class="panel">
                        <p class="panel-heading">
                            Most Viewed Pages
                        </p>
                        {% for page in pages %}
                            <a class="panel-block" href="{% url 'bookmarks:goto' %}?page_id={{ page.id }}"
                               target="_blank">
                                {{ page.title }}
                                {% if page.views > 1 %}
                                    <span class="tag is-info is-small">{{ page.views }} views</span>
                                {% elif page.views == 1 %}
                                    <span class="tag is-info is-small">{{ page.views }} view</span>
                                {% endif %}
                            </a>
                        {% endfor %}

                        {% else %}
                        <p class="panel-block">No page found.</p>
                    </nav>

                {% endif %}
            </div>

        </div>
    </div>

{% endblock %}

bookmarks/templates/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block content %}
    <div class="container">
        <form action="{% url 'bookmarks:login' %}" method="post">
            {% csrf_token %}

            <label for="username" class="label">Username</label>
            <input type="text" id="username" name="username" class="input">

            <label for="password" class="label">Password</label>
            <input type="password" id="password" name="password" class="input">

            <input class="button is-info" type="submit" name="submit" value="Login">
        </form>
    </div>
{% endblock %}

bookmarks/templates/register.html
{% extends 'base.html' %}

{% block title %} Register {% endblock %}

{% block content %}
    <div class="container">
        {% if registered %}
            <h2>Thank you for registering.</h2>
            <p>Return to <a href="{% url 'index' %}">Homepage</a></p>
        {% else %}
            <form id="user_form" action="{% url 'bookmarks:register' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                {% for field in user_form %}
                    {% if field.errors %}
                        <div class="notification is-danger">{{ field.errors }}</div>
                    {% endif %}
                    <p>
                        <label class="label">{{ field.label }}</label>
                        {{ field }}
                    </p>

                {% endfor %}
                {% for field in profile_form %}
                    {% if field.errors %}
                        <div class="notification is-danger">{{ field.errors }}</div>
                    {% endif %}
                    <p>
                        <label class="label">{{ field.label }}</label>
                        {{ field }}
                    </p>

                {% endfor %}


                <input class="button is-info" type="submit" name="submit" value="Register">
            </form>
        {% endif %}
    </div>
{% endblock %}